---
# file: roles/clamav/main.yaml

- name: Install ClamAV
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - clamav
    - clamav-freshclam
    - clamav-daemon

- name: Ensure ClamAV daemon is running (if configured).
  become: true
  service:
    name: clamav-daemon
    state: started
    enabled: yes

- name: Ensure ClamAV freshclam daemon is running (if configured).
  become: true
  service:
    name: clamav-freshclam
    state: started
    enabled: yes