---
# file: roles/apt/main.yaml

# Wait for APT lock to be released
- name: wait until apt lock is released
  shell: lsof -w /var/lib/apt/lists/lock | wc -l
  register: lock
  until: lock.stdout == "0"
  retries: 10
  delay: 10

- name: wait until apt lock_frontend is released
  shell: lsof -w /var/lib/dpkg/lock-frontend | wc -l
  register: lock_frontend
  until: lock_frontend.stdout == "0"
  retries: 10
  delay: 10

# Force APT to update all repositories
- name: Update APT Repo
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

# Upgrade all available packages via APT
- name: Upgrade All Packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes